# Generated by Django 3.2.9 on 2021-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0005_auto_20211119_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
