# Generated by Django 3.2.9 on 2021-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0007_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransaction',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
