# Generated by Django 3.2.9 on 2021-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0008_topuptransaction_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alcoholic',
            field=models.BooleanField(default=False),
        ),
    ]
