# Generated by Django 3.2.9 on 2021-12-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0011_rename_cards_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletransaction',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='topuptransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
