# Generated by Django 4.0 on 2021-12-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0012_auto_20211206_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mongoose_app.user'),
        ),
        migrations.AlterField(
            model_name='topuptransaction',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mongoose_app.user'),
        ),
    ]
