# Generated by Django 4.0 on 2021-12-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0015_vat_product_vat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vat',
            options={'verbose_name': 'BTW percentage', 'verbose_name_plural': 'BTW percentages'},
        ),
        migrations.AddField(
            model_name='producttransactions',
            name='product_vat',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
