# Generated by Django 4.0 on 2021-12-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0016_alter_vat_options_producttransactions_product_vat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttransactions',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongoose_app.vat', verbose_name='BTW'),
        ),
    ]
