# Generated by Django 4.0 on 2022-01-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0017_alter_producttransactions_options_alter_product_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=32)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongoose_app.card')),
            ],
        ),
    ]
