# Generated by Django 4.0 on 2022-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0018_cardconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
