# Generated by Django 4.0 on 2022-01-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0018_alter_product_image'),
        ('mongoose_app', '0020_alter_user_user_id'),
    ]

    operations = [
    ]
