# Generated by Django 4.0.2 on 2022-02-08 18:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0021_merge_20220120_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='topuptransaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
