# Generated by Django 4.0.2 on 2022-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0022_alter_saletransaction_transaction_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='topuptransaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
