# Generated by Django 4.0.2 on 2022-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0025_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Pin'), (2, 'Credit card')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
