# Generated by Django 4.0 on 2025-02-23 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0029_idealtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealtransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topuptransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
