# Generated by Django 4.0 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0030_alter_idealtransaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
