# Generated by Django 4.0 on 2025-03-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0030_alter_idealtransaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransactions',
            name='status',
            field=models.IntegerField(choices=[(1, 'SALE'), (2, 'RODENTS'), (3, 'SPOILED'), (4, 'RECOUNT'), (5, 'BROKEN'), (6, 'OTHER')], default=1),
        ),
    ]
