# Generated by Django 4.0 on 2025-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0031_card_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
