# Generated by Django 4.0 on 2026-08-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0035_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
