# Generated by Django 4.0 on 2026-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0036_remove_user_birthday_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='wrapped_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='wrapped_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
