# Generated by Django 4.0 on 2026-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoose_app', '0037_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stockKamer',
        ),
        migrations.AddField(
            model_name='product',
            name='stockKelder',
            field=models.IntegerField(default=0),
        ),
    ]
